(() => {
  'use strict';
  const W=window.Workflow, cfg=window.EXAMFLOW_CONFIG||{}, $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icons={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',tasks:'<path d="m4 6 2 2 3-4M12 6h8M4 13l2 2 3-4M12 13h8M4 20h16"/>',courses:'<path d="M3 4h6a4 4 0 0 1 3 2 4 4 0 0 1 3-2h6v16h-6a4 4 0 0 0-3 1 4 4 0 0 0-3-1H3zM12 6v15"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4M17 3v4M3 11h18M8 15h2M14 15h2"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',check:'<path d="m5 12 4 4L19 6"/>',plus:'<path d="M12 5v14M5 12h14"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',logout:'<path d="M9 4H4v16h5M9 12h12m-5-5 5 5-5 5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 15v6h16v-6"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6"/>'};
  const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.tasks}</svg>`;
  const fmt=d=>d?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',timeZone:'Asia/Dhaka'}).format(new Date(d+'T12:00:00Z')):'No deadline';
  const data=()=>store.data, admin=()=>W.isAdmin(store.profile), fid=()=>store.profile?.faculty_id;
  const name=id=>data().faculty?.find(f=>f.id===id)?.full_name||'Unassigned';
  const all=()=>W.activities(data()), mine=()=>all().filter(a=>a.owner===fid());
  const options=(items,value)=>items.map(x=>{const [v,l]=Array.isArray(x)?x:[x,W.text(x)];return `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`;}).join('');
  const badge=(status,kind)=>`<span class="badge ${W.done(kind,status)?'complete':status==='blocked'?'blocked':''}">${esc(W.text(status))}</span>`;
  let store=new window.WorkflowStore.Store(null), view='home', bucket='attention', search='', courseId=null, calendarOffset=0, importRows=null, importFingerprint=null, refreshToken=0, busy=false;
  let priorFocus=null;
  const notice=(msg,type='')=>{const n=document.createElement('div');n.className='toast '+type;n.setAttribute('role',type==='error'?'alert':'status');n.textContent=msg;$('#toasts').append(n);setTimeout(()=>n.remove(),6000);};
  const button=(label,action,cls='secondary',attrs='')=>`<button class="button ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
  function empty(title,body=''){return `<div class="empty-state"><span class="empty-icon">${icon('check')}</span><h3>${esc(title)}</h3><p>${esc(body)}</p></div>`;}
  function header(kicker,title,body='',action=''){return `<div class="page-heading"><div><p class="eyebrow">${esc(kicker)}</p><h1>${esc(title)}</h1>${body?`<p class="subtitle">${esc(body)}</p>`:''}</div>${action}</div>`;}
  function taskRow(a){
    const b=W.bucket(a),late=!a.finished&&!a.cancelled&&a.date&&W.days(a.date)<0;
    return `<button class="task-row" data-activity="${esc(a.id)}"><span class="task-icon ${a.kind}">${icon(a.finished?'check':a.kind==='ct'?'calendar':a.kind==='outline'?'courses':'tasks')}</span><span class="task-copy"><span class="task-course">${esc(a.course.course_code)}<span class="separator">/</span>${esc(a.row.section||a.row.scope||W.LABELS[a.kind])}</span><strong>${esc(a.title)}</strong><span class="task-detail">${a.waiting.length?'Waiting for '+esc(a.waiting.map(x=>x?.title||'prerequisite').join(', ')):esc(name(a.owner))}</span></span><span class="task-end"><span class="${late?'late':''}">${a.finished?'Completed':a.cancelled?'Cancelled':late?'Update needed · '+fmt(a.date):fmt(a.date)}</span>${badge(a.status,a.kind)}</span>${icon('arrow','row-arrow')}</button>`;
  }
  function filtered(items){const q=search.trim().toLowerCase();return items.filter(a=>!q||[a.title,a.course.course_code,a.course.title,name(a.owner)].join(' ').toLowerCase().includes(q)).sort(W.sort);}
  function shell(content){
    const d=data(),p=store.profile,first=name(fid()).replace(/^Faculty /,'').split(' ')[0],nav=[['home','home','Overview'],['tasks','tasks','My work'],['courses','courses','Courses'],['calendar','calendar','Calendar'],['notifications','bell','Inbox']];
    if(admin())nav.push(['admin','settings','Manage']);
    return `<a class="skip-link" href="#main">Skip to content</a><header class="topbar"><a class="wordmark" href="#home" data-nav="home"><span class="brand-symbol"><i></i><i></i><i></i></span>BME<span class="wordmark-light">Workflow</span></a><nav aria-label="Main navigation">${nav.map(([v,i,l])=>`<button class="nav-item ${view===v?'active':''}" data-nav="${v}" ${view===v?'aria-current="page"':''}>${icon(i)}<span>${l}</span></button>`).join('')}</nav><div class="topbar-user"><span class="live-dot"></span><span>${store.demo?'Preview':esc(W.text(p.app_role))}</span><button class="avatar" data-action="account" aria-label="Account and sign out">${esc(first.slice(0,1))}</button></div></header>${store.demo?'<div class="demo-strip">Interactive preview · fictional faculty · changes last for this visit <a href="'+esc(location.pathname)+'">Exit preview '+icon('arrow')+'</a></div>':''}<div class="workspace"><div class="workspace-context"><span>${esc(cfg.institutionName||'Department of Biomedical Engineering')}<span class="context-dot">·</span>BUET</span><label class="term-selector"><span class="sr-only">Academic term</span><select id="term-select">${options((d.terms||[d.term]).map(t=>[t.id,t.name]),d.term?.id)}</select></label></div><main id="main" tabindex="-1">${content}</main><footer><span>BME Workflow<span class="context-dot">·</span>A little clarity. A lot of progress.</span><span>${store.demo?'Preview workspace':'Verified access'} ${icon('shield')}</span></footer></div>`;
  }
  function home(){
    const items=mine(),attention=items.filter(a=>W.bucket(a)==='attention'),upcoming=items.filter(a=>W.bucket(a)==='upcoming'),done=items.filter(a=>a.finished),pct=W.progress(items),t=data().term;
    return `<section class="hero"><div><p class="eyebrow">YOUR DAY, IN FOCUS</p><h1>Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'},<br><span>${esc(name(fid()).replace(/^Faculty /,'').split(' ')[0])}.</span></h1><p>A clear view of what’s next.<br>More room for the work that matters.</p>${button('View my work '+icon('arrow'),'my-work','primary')}</div><div class="hero-art" aria-label="${pct??0} percent of your required activities complete"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="progress-orb" style="--progress:${pct||0}"><div><span class="orb-label">YOUR PROGRESS</span><strong>${pct??'—'}<small>${pct===null?'':'%'}</small></strong><span>${done.length} activities complete</span></div></div><span class="floating-note">${icon('check')}One step at a time.</span></div></section><section class="metrics" aria-label="Your activity summary">${[[attention.length,'Needs my action','A good place to start','attention'],[upcoming.length,'Coming up','Your next scheduled work','upcoming'],[items.filter(a=>W.bucket(a)==='waiting').length,'Waiting on others','We’ll show what’s needed','waiting'],[done.length,'Completed','Progress, made visible','completed']].map(([n,l,s,b])=>`<button class="metric" data-bucket-link="${b}"><span>${l}${icon('arrow')}</span><strong>${n.toString().padStart(2,'0')}</strong><small>${s}</small></button>`).join('')}</section><div class="dashboard-grid"><section class="panel focus-panel"><div class="panel-heading"><div><p class="eyebrow">THE NEXT STEP</p><h2>Needs your attention</h2></div><button class="text-button" data-nav="tasks">View all ${icon('arrow')}</button></div>${filtered(attention).slice(0,5).map(taskRow).join('')||empty('You’re all caught up','Your next activities are waiting in Upcoming.')}</section><aside class="panel term-panel"><p class="eyebrow">THE BIGGER PICTURE</p><h2>A term in motion.</h2><p class="muted">${esc(t?.name||'No term configured')}</p><div class="week-display"><strong>${t?.latest_completed_week||0}</strong><span>of ${t?.total_teaching_weeks||14}<br>weeks complete</span></div><div class="week-bars" aria-hidden="true">${Array.from({length:t?.total_teaching_weeks||14},(_,i)=>`<i class="${i<(t?.latest_completed_week||0)?'filled':''}"></i>`).join('')}</div><p class="small muted">${t?.calendar_status==='paused'?'Academic progression is paused. '+esc(t.pause_reason):'Progress follows the approved academic calendar.'}</p><div class="term-next"><span class="mini-label">ON THE HORIZON</span>${upcoming.sort(W.sort).slice(0,2).map(a=>`<button data-activity="${esc(a.id)}"><span class="date-tile">${fmt(a.date)}</span><span><strong>${esc(a.course.course_code)}</strong><small>${esc(a.title)}</small></span></button>`).join('')||'<p class="small muted">No upcoming deadlines.</p>'}</div></aside></div>`;
  }
  function tasks(){const items=mine();return header('MAKE SPACE FOR PROGRESS','Your work. One place.','Every assigned activity, from first draft to final handover.')+`<div class="toolbar"><div class="segmented" role="group" aria-label="Task groups">${[['attention','Needs my action'],['waiting','Waiting on others'],['upcoming','Upcoming'],['completed','Completed']].map(([b,l])=>`<button class="${b===bucket?'selected':''}" data-bucket="${b}" aria-pressed="${b===bucket}">${l}<span>${items.filter(a=>W.bucket(a)===b).length}</span></button>`).join('')}</div>${searchBox()}</div><section class="panel task-list">${filtered(items.filter(a=>W.bucket(a)===bucket)).map(taskRow).join('')||empty(search?'No matching activities':'Nothing here just yet',search?'Try a course code or another search.':'Activities appear here when their status changes.')}</section>`;}
  function searchBox(){return `<label class="search">${icon('search')}<span class="sr-only">Search courses and activities</span><input id="search" placeholder="Search your workspace" value="${esc(search)}" type="search" autocomplete="off"></label>`;}
  function courses(){
    const cs=data().courses.filter(c=>admin()||all().some(a=>a.course.id===c.id&&a.owner===fid())||data().courseFaculty.some(r=>r.course_id===c.id&&r.faculty_id===fid())).filter(c=>[c.course_code,c.title].join(' ').toLowerCase().includes(search.toLowerCase()));
    return header('CONNECTED BY PURPOSE','Your courses.', 'The people, activities, and progress behind each course.',admin()?button(icon('plus')+' Add course','new-course'):searchBox())+`<div class="course-grid">${cs.map((c,i)=>{const items=all().filter(a=>a.course.id===c.id),pct=W.progress(items);return `<button class="course-card tone-${i%4}" data-course="${esc(c.id)}"><div class="course-card-top"><span class="mini-label">${esc(W.text(c.course_type))}</span>${icon('arrow')}</div><span class="course-code">${esc(c.course_code)}</span><h2>${esc(c.title)}</h2><div class="course-card-bottom"><span>${items.length} activities<span class="context-dot">·</span>${esc(c.status)}</span><div class="progress-track"><i style="width:${pct||0}%"></i></div><div class="course-progress"><span>Overall progress</span><strong>${pct??'—'}${pct===null?'':'%'}</strong></div></div></button>`;}).join('')||empty('No courses assigned','Your courses appear after your faculty identity is assigned.')}</div>`;
  }
  function course(){
    const c=data().courses.find(c=>c.id===courseId);if(!c)return empty('Course unavailable');const items=all().filter(a=>a.course.id===c.id),manage=W.manages(data(),c.id,store.profile);
    return `<button class="text-button back-link" data-nav="courses">← All courses</button>`+header(c.course_code,c.title,`${W.text(c.course_type)} · ${data().term.name} · ${W.text(c.status)}`,admin()?button('Course settings','edit-course'): '')+`<div class="course-summary panel"><div><span class="mini-label">PROGRESS</span><strong>${W.progress(items)??'—'}%</strong></div><div><span class="mini-label">COURSE TEAM</span><p>${esc([...new Set(data().courseFaculty.filter(r=>r.course_id===c.id).map(r=>name(r.faculty_id)))].join(' · ')||'No teachers assigned')}</p></div>${manage?`<div class="actions">${button(icon('plus')+' Class test','new-ct')}${c.course_type!=='theory'?button('Configure activities','generate'):''}</div>`:''}</div><section class="panel"><div class="panel-heading"><h2>Course activity</h2><span class="muted small">${items.filter(a=>a.finished).length} complete · ${items.filter(a=>!a.owner).length} unassigned</span></div>${items.map(taskRow).join('')||empty('Ready for a fresh start','Configure activities for this course.')}</section>`;
  }
  function calendar(){
    const today=W.today(),base=new Date(today+'T12:00:00Z');base.setUTCDate(1);base.setUTCMonth(base.getUTCMonth()+calendarOffset);
    const year=base.getUTCFullYear(),month=base.getUTCMonth(),prefix=`${year}-${String(month+1).padStart(2,'0')}`,days=new Date(Date.UTC(year,month+1,0)).getUTCDate(),offset=(base.getUTCDay()+6)%7;
    const events=store.demo?all().filter(a=>a.date).map(a=>({id:a.id,date:a.date,course_code:a.course.course_code,title:a.title,kind:W.LABELS[a.kind],status:a.status})):data().department?.calendar||[];
    const milestones=(data().termMilestones||[]).filter(m=>!m.course_id).map(m=>({id:m.id,date:m.milestone_date,course_code:'Department',title:W.text(m.milestone_type),kind:'Deadline'}));
    const listed=events.concat(milestones).filter(e=>e.date?.startsWith(prefix)&&e.status!=='cancelled').sort((a,b)=>a.date.localeCompare(b.date));
    return header('A SHARED RHYTHM','The department calendar.','Shared schedules, with private work kept private.')+`<section class="panel calendar-panel"><div class="panel-heading"><h2>${base.toLocaleDateString('en-GB',{month:'long',year:'numeric',timeZone:'UTC'})}</h2><div class="actions">${button('←','prev-month','icon-button','aria-label="Previous month"')}${button('Today','this-month')}${button('→','next-month','icon-button','aria-label="Next month"')}</div></div><div class="calendar-grid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<span class="calendar-day-label">${d}</span>`).join('')}${'<div class="calendar-cell blank"></div>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const date=prefix+'-'+String(i+1).padStart(2,'0');return `<div class="calendar-cell ${date===today?'is-today':''}"><span class="day-number">${i+1}</span>${listed.filter(e=>e.date===date).slice(0,3).map(e=>`<span class="calendar-event" title="${esc(e.title)}">${esc(e.course_code)}</span>`).join('')}${listed.filter(e=>e.date===date).length>3?'<small>+'+(listed.filter(e=>e.date===date).length-3)+' more</small>':''}</div>`;}).join('')}</div></section><section class="panel agenda"><div class="panel-heading"><h2>This month’s agenda</h2><span class="muted small">${listed.length} events</span></div>${listed.map(e=>`<div class="agenda-row"><span class="date-tile">${fmt(e.date)}</span><div><strong>${esc(e.title)}</strong><span>${esc(e.course_code)} · ${esc(e.kind)}</span></div>${badge(e.status||'scheduled')}</div>`).join('')||empty('An open calendar','No events are scheduled for this month.')}</section>`;
  }
  function inbox(){return header('STAY IN THE LOOP','A little less chasing.','Updates, handoffs, and requests in one quiet place.')+`<section class="panel">${(data().notifications||[]).map(n=>{const read=data().receipts?.some(r=>r.notification_id===n.id);return `<article class="inbox-row ${read?'read':''}"><span class="task-icon">${icon('bell')}</span><div><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p><small>${esc(n.created_at?new Date(n.created_at).toLocaleString():'Just now')}</small></div>${read?'<span class="small muted">Read</span>':button('Mark read','read-notice','secondary',`data-id="${esc(n.id)}"`)}</article>`;}).join('')||empty('Nothing new','Updates will appear as your work moves forward.')}</section><section class="panel"><div class="panel-heading"><h2>Requests</h2></div>${(data().requests||[]).map(r=>`<div class="inbox-row"><div><h3>${esc(W.text(r.request_type))}</h3><p>${esc(r.reason)}</p><small>${esc(r.status)}${r.resolution?' · '+esc(r.resolution):''}</small></div>${r.status==='pending'&&admin()?button('Review','resolve-request','secondary',`data-id="${esc(r.id)}"`):''}</div>`).join('')||empty('No open requests','Ask for an extension or reassignment from any activity.')}</section>`;}
  function manage(){
    const items=all(),missing=items.filter(a=>!a.finished&&!a.cancelled&&(!a.owner||!a.date)),allowed=data().allowed||[];
    return header('MAKE THE EXCEPTIONS VISIBLE','A smoother department.','Configure ownership once. Keep your attention on what needs it.')+`<div class="admin-actions">${button(icon('plus')+' Faculty approval','new-faculty')}${button(icon('plus')+' Course offering','new-course')}${button('Term & calendar','term')}${button(icon('upload')+' Review CT import','import')}${button('Refresh workspace','refresh')}</div><div class="dashboard-grid"><section class="panel"><div class="panel-heading"><h2>Setup needs attention</h2><span class="count-pill">${missing.length}</span></div>${missing.slice(0,12).map(taskRow).join('')||empty('Setup is looking good')}</section><section class="panel"><div class="panel-heading"><h2>Faculty access</h2><span class="small muted">${data().faculty.length} identities</span></div>${data().faculty.map(f=>{const a=allowed.find(a=>a.faculty_id===f.id);return `<button class="faculty-row" data-faculty="${esc(f.id)}"><span class="avatar">${esc(f.full_name[0])}</span><span><strong>${esc(f.full_name)}</strong><small>${esc(a?.email||f.email||'Email not mapped')}</small></span><span class="badge">${store.demo?'Preview':!a?'Unmapped':a.active?'Approved':'Revoked'}</span></button>`;}).join('')}</section></div><section class="panel"><div class="panel-heading"><h2>Delivery & history</h2></div><div class="health-row"><span>${(data().outbox||[]).filter(x=>x.status==='failed').length} failed deliveries</span><span>${(data().outbox||[]).filter(x=>x.status==='pending').length} queued</span><span>Changes are recorded in the audit log</span></div>${(data().audit||[]).slice(0,12).map(a=>`<div class="audit-row"><span>${esc(W.text(a.table_name))}</span><span>${esc(a.action)}</span><time>${esc(new Date(a.created_at).toLocaleString())}</time></div>`).join('')}</section>`;
  }
  function render(){
    const content=courseId?course():({home,tasks,courses,calendar,notifications:inbox,admin:manage}[view]||home)();$('#app').innerHTML=shell(content);bind();
  }
  function bind(){
    document.querySelectorAll('[data-nav]').forEach(el=>el.onclick=e=>{e.preventDefault();view=el.dataset.nav;courseId=null;search='';render();$('#main').focus();});
    document.querySelectorAll('[data-bucket-link]').forEach(el=>el.onclick=()=>{view='tasks';bucket=el.dataset.bucketLink;render();});
    document.querySelectorAll('[data-bucket]').forEach(el=>el.onclick=()=>{bucket=el.dataset.bucket;render();});
    document.querySelectorAll('[data-activity]').forEach(el=>el.onclick=()=>editActivity(all().find(a=>a.id===el.dataset.activity)));
    document.querySelectorAll('[data-course]').forEach(el=>el.onclick=()=>{courseId=el.dataset.course;view='courses';render();});
    document.querySelectorAll('[data-faculty]').forEach(el=>el.onclick=()=>facultyForm(data().faculty.find(f=>f.id===el.dataset.faculty)));
    document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>action(el.dataset.action,el.dataset));
    if($('#search'))$('#search').oninput=e=>{const pos=e.target.selectionStart;search=e.target.value;render();$('#search').focus();try{$('#search').setSelectionRange(pos,pos);}catch{}};
    $('#term-select').onchange=async e=>{store.termId=e.target.value;courseId=null;await refresh();};
  }
  async function refresh(){const token=++refreshToken;try{await store.load();if(token===refreshToken)render();}catch(e){notice(e.message,'error');}}
  function modal(title,body){
    priorFocus=document.activeElement;$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;
    if(!$('#dialog').open)$('#dialog').showModal();$('#dialog-body').querySelector('input,select,textarea,button')?.focus();
  }
  function close(){if(busy)return;$('#dialog').close();priorFocus?.focus();}
  function field(label,name,value='',type='text',attrs=''){return `<label class="field"><span>${esc(label)}</span><input type="${type}" name="${name}" value="${esc(value)}" ${attrs}></label>`;}
  function select(label,name,items,value=''){return `<label class="field"><span>${esc(label)}</span><select name="${name}">${options(items,value)}</select></label>`;}
  function formEnd(label='Save changes'){return `<div id="form-error" class="form-error" role="alert"></div><div class="form-actions"><span class="small muted">${store.demo?'Preview · changes are not persisted':'Saved securely to your workspace'}</span><button class="button primary" type="submit">${label} ${icon('arrow')}</button></div></form>`;}
  function wireSave(handler){$('#editor').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const form=e.currentTarget,btn=form.querySelector('[type=submit]'),old=btn.innerHTML;btn.disabled=true;btn.textContent='Saving…';$('#form-error').textContent='';try{await handler(new FormData(form));busy=false;close();render();notice(store.demo?'Updated in this preview':'Saved');}catch(err){busy=false;$('#form-error').textContent=err.saved?'Saved, but refresh failed. Close and refresh before editing again.':err.message;btn.disabled=!!err.saved;btn.innerHTML=old;}};}
  function editActivity(a){
    if(!a)return;const manages=W.manages(data(),a.course.id,store.profile),owns=a.owner===fid()||admin(),editable=(owns||manages)&&a.course.status!=='archived'&&(data().term.active||store.demo),r=a.row;
    const dates={ct:[['Scheduled date','scheduled_date'],['Marking deadline','marking_due_date'],['Publication deadline','publication_due_date']],session:[['Session date','date'],['Report deadline','report_deadline']],assessment:[['Scheduled date','scheduled_date'],['Upload deadline','due_date']],outline:[['Sharing deadline','due_date']],feedback:[['Deadline','deadline']],car:[['Deadline','deadline']],grade:[['Deadline','due_date']]};
    modal(a.title,`<div class="activity-context"><span>${esc(a.course.course_code)} · ${esc(r.section||r.scope||W.LABELS[a.kind])}</span><strong>${esc(name(a.owner))}</strong></div>${a.waiting.length?`<div class="callout">${icon('clock')}<span>Waiting for ${esc(a.waiting.map(x=>x?.title||'prerequisite').join(', '))}.</span></div>`:''}${!editable?'<p class="callout">You can view this activity. Updates belong to its assigned owner.</p>':''}<form id="editor"><fieldset ${editable?'':'disabled'}>${owns?select('Status','status',W.STATES[a.kind],a.status):`<p>${badge(a.status,a.kind)}</p>`}<div class="form-grid">${(dates[a.kind]||[]).map(([l,k])=>field(l,k,r[k]||'','date',manages||a.kind==='ct'&&k==='scheduled_date'||a.kind==='session'&&k==='date'?'':'disabled')).join('')}${a.kind==='ct'?field('Start time','scheduled_time',r.scheduled_time||r.time||'','time')+field('Duration (minutes)','duration_minutes',r.duration_minutes||30,'number','min="1" max="480"'):''}</div>${manages?select('Accountable owner',a.kind==='session'?'assigned_faculty':'responsible_faculty',[['','Unassigned'],...data().faculty.filter(f=>data().courseFaculty.some(cf=>cf.course_id===a.course.id&&cf.faculty_id===f.id)).map(f=>[f.id,f.full_name])],a.owner):''}${owns?`${field('Evidence link (HTTPS)','evidence_url',r.evidence_url||'','url','placeholder="https://…"')}<label class="field"><span>Notes / blocker</span><textarea name="notes" rows="3" placeholder="What changed, or what’s getting in the way?">${esc(r.notes||'')}</textarea></label>`:''}<label class="field"><span>Reason for correction or schedule change</span><textarea name="change_reason" rows="2" placeholder="Required for rescheduling, reopening, or administrative corrections"></textarea></label></fieldset><div class="activity-meta">Last changed: ${r.updated_at?esc(new Date(r.updated_at).toLocaleString()):'No recorded change'}</div>${editable?formEnd():'</form>'}${owns&&a.course.status!=='archived'?'<button class="text-button request-link" id="request-change">Request an extension or reassignment '+icon('arrow')+'</button>':''}`);
    if(editable)wireSave(async fd=>{const patch=Object.fromEntries(fd);if(!['ct','session','assessment','outline','feedback','car'].includes(a.kind))delete patch.responsible_faculty;if(!manages){delete patch.responsible_faculty;delete patch.assigned_faculty;}
      for(const k of Object.keys(patch)){if(k.endsWith('_date')||['date','deadline','due_date','report_deadline','scheduled_time','responsible_faculty','assigned_faculty'].includes(k))patch[k]=patch[k]||null;}
      if(patch.duration_minutes)patch.duration_minutes=+patch.duration_minutes;await store.save(a,patch);
    });
    if($('#request-change'))$('#request-change').onclick=()=>requestForm(a);
  }
  function requestForm(a){modal('Ask for a change',`<p class="muted">${esc(a.course.course_code)} · ${esc(a.title)}</p><form id="editor">${select('Request type','request_type',['extension','reassignment'],'extension')}${field('Proposed deadline (for an extension)','proposed_date','','date')}<label class="field"><span>Reason</span><textarea name="reason" required rows="4"></textarea></label>${formEnd('Submit request')}`);wireSave(async fd=>{if(store.demo){data().requests.push({id:crypto.randomUUID(),reason:fd.get('reason'),request_type:fd.get('request_type'),status:'pending'});return;}await store.mutate('workflow_request',{p_course:a.course.id,p_kind:a.kind,p_id:a.row.id||null,p_task:a.key,p_type:fd.get('request_type'),p_reason:fd.get('reason'),p_date:fd.get('proposed_date')||null});});}
  function courseForm(c={}){
    const a=data().primaryAssignments.find(a=>a.course_id===c.id)||data().sessionalGradeAssignments.find(a=>a.course_id===c.id)||{},members=data().courseFaculty.filter(r=>r.course_id===c.id),fs=[['','Unassigned'],...data().faculty.map(f=>[f.id,f.full_name])];
    modal(c.id?'Course settings':'A new course offering',`<form id="editor"><div class="form-grid">${field('Course code','course_code',c.course_code||'','text',c.id?'readonly':'required')}${select('Course type','course_type',['theory','sessional'],c.course_type||'theory')}${field('Course title','title',c.title||'','text','required')}${field('Cohort / batch','batch',c.batch||'')}</div><p class="mini-label">COURSE TEAM</p><div class="teacher-options">${data().faculty.map(f=>`<label><input type="checkbox" name="teachers" value="${esc(f.id)}" ${members.some(r=>r.faculty_id===f.id)?'checked':''}>${esc(f.full_name)}</label>`).join('')}</div>${select('Course coordinator','coordinator',fs,members.find(r=>['coordinator','sessional_coordinator'].includes(r.role))?.faculty_id||'')}<div class="form-grid">${[['preparer_a','Question preparer · A'],['preparer_b','Question preparer · B'],['moderator_1','Moderator · 01'],['moderator_2','Moderator · 02'],['scrutinizer','Scrutinizer'],['preparer','Sessional gradesheet preparer']].map(([k,l])=>select(l,k,fs,a[k]||'')).join('')}${field('Question deadline','question_deadline',c.question_deadline||'','date')}${field('Exam date','exam_date',c.exam_date||'','date')}${field('Final gradesheet deadline','final_gradesheet_deadline',c.final_gradesheet_deadline||'','date')}</div>${select('Publication','status',['draft','published','archived'],c.status||'draft')}<label class="field"><span>Reason for changes to an existing offering</span><textarea name="change_reason"></textarea></label>${formEnd()}`);
    wireSave(async fd=>{if(store.demo)throw Error('Course setup needs a connected workspace. Activity updates can be explored in the preview.');const p=Object.fromEntries(fd),assign=Object.fromEntries(['preparer_a','preparer_b','moderator_1','moderator_2','scrutinizer','preparer'].map(k=>[k,p[k]||null]));await store.mutate('workflow_course',{p_id:c.id||null,p_term:data().term.id,p_patch:{course_code:p.course_code,title:p.title,course_type:p.course_type,batch:p.batch,status:p.status,question_deadline:p.question_deadline,exam_date:p.exam_date,final_gradesheet_deadline:p.final_gradesheet_deadline,coordinator:p.coordinator,change_reason:p.change_reason,expected_revision:c.revision??null},p_teachers:fd.getAll('teachers'),p_assignments:assign});});
  }
  function facultyForm(f={}){const a=(data().allowed||[]).find(a=>a.faculty_id===f.id)||{};modal('Faculty access',`<form id="editor">${field('Full name','name',f.full_name||'','text','required')}${field('Approved email','email',a.email||f.email||'','email','required')}${select('Department role','role',['faculty','admin','hod'],a.app_role||'faculty')}${select('Access','active',[['true','Approved'],['false','Revoked']],String(a.active??true))}<p class="small muted">The faculty member verifies this exact email before academic records become available. Changing it revokes the previous mapping.</p>${formEnd()}`);wireSave(async fd=>{if(store.demo)throw Error('Faculty approvals require a connected workspace.');await store.mutate('workflow_faculty',{p_id:f.id||null,p_name:fd.get('name'),p_email:fd.get('email'),p_role:fd.get('role'),p_active:fd.get('active')==='true'});});}
  function termForm(){const t=data().term;modal('Term & academic calendar',`<form id="editor">${field('Term name','name',t.name,'text','required')}<div class="form-grid">${field('Total teaching weeks','total_teaching_weeks',t.total_teaching_weeks,'number','min="1" max="52" required')}${field('Completed teaching weeks','latest_completed_week',t.latest_completed_week,'number','min="0" max="52" required')}</div>${select('Academic progression','calendar_status',['active','paused'],t.calendar_status)}${field('Reason / calendar note','pause_reason',t.pause_reason||'','text','required')}<p class="small muted">Calendar progression never completes academic work. Week ranges can include teaching breaks.</p><div class="week-editor">${Array.from({length:t.total_teaching_weeks},(_,i)=>{const w=data().academicWeeks.find(w=>w.week_no===i+1)||{};return `<div><span>Week ${i+1}</span>${field('Starts','start_'+(i+1),w.starts_on||'','date')}${field('Ends','end_'+(i+1),w.ends_on||'','date')}</div>`;}).join('')}</div>${formEnd()}</form><button class="text-button" id="new-term">Start a new term →</button>`);wireSave(async fd=>{if(store.demo)throw Error('Calendar settings require a connected workspace.');const p=Object.fromEntries(fd);p.total_teaching_weeks=+p.total_teaching_weeks;p.latest_completed_week=+p.latest_completed_week;p.weeks=Array.from({length:p.total_teaching_weeks},(_,i)=>({week_no:i+1,starts_on:p['start_'+(i+1)]||null,ends_on:p['end_'+(i+1)]||null}));await store.mutate('workflow_term',{p_id:t.id,p_patch:p});});$('#new-term').onclick=()=>{modal('Start a new term',`<form id="editor">${field('Term name','name','','text','required')}${field('Stable term code','code','','text','required placeholder="2027-01"')}<p class="muted small">Creates an inactive term. Old offerings and completed work remain intact. Add new course offerings from Manage.</p>${formEnd('Create term')}`);wireSave(async fd=>{if(store.demo)throw Error('Term creation requires a connected workspace.');await store.mutate('workflow_term',{p_id:null,p_patch:Object.fromEntries(fd)});});};}
  function newCt(){const c=data().courses.find(c=>c.id===courseId);modal('Plan a class test',`<form id="editor"><div class="form-grid">${field('CT number','ct_number',1,'number','min="1" required')}${field('Title','title','Class test','text','required')}${field('Teaching section','section','Entire Course')}${field('Cohort / batch','batch',c.batch||'','text','required')}${field('Scheduled date','scheduled_date','','date')}${field('Start time','scheduled_time','','time')}${field('Duration (minutes)','duration_minutes',30,'number','min="1" max="480" required')}${field('Marking deadline','marking_due_date','','date')}${field('Publication deadline','publication_due_date','','date')}</div>${select('Accountable owner','responsible_faculty',[['','Unassigned'],...data().faculty.filter(f=>data().courseFaculty.some(cf=>cf.course_id===c.id&&cf.faculty_id===f.id)).map(f=>[f.id,f.full_name])])}${formEnd('Create class test')}`);wireSave(async fd=>{const p=Object.fromEntries(fd);p.ct_number=+p.ct_number;p.duration_minutes=+p.duration_minutes;for(const k of Object.keys(p))if(!p[k])p[k]=null;p.status=p.scheduled_date?'scheduled':'not_planned';if(store.demo){data().classTests.push({...p,id:crypto.randomUUID(),course_id:c.id,revision:1});return;}await store.mutate('workflow_save_activity',{p_kind:'ct',p_course:c.id,p_patch:p});});}
  function generate(){const c=data().courses.find(c=>c.id===courseId);modal('Configure sessional activities',`<form id="editor">${select('Activity group','kind',[['sessions','Teaching sessions'],['component','Assessment component']])}${field('Component name','name','Report','text','required')}<div class="form-grid">${field('Quantity','quantity',1,'number','min="1" max="100" required')}${field('Counted quantity','counted_quantity',1,'number','min="0" max="100" required')}${field('Marks per assessment','marks_each',0,'number','min="0" step="0.01" required')}${field('Teaching section / scope','scope','Entire Course','text','required')}</div>${select('Owner','owner',[['','Unassigned'],...data().faculty.filter(f=>data().courseFaculty.some(cf=>cf.course_id===c.id&&cf.faculty_id===f.id)).map(f=>[f.id,f.full_name])])}<p class="small muted">Existing sequences keep their IDs and progress. Cancel surplus sessions explicitly before reducing the count.</p>${formEnd('Generate activities')}`);wireSave(async fd=>{if(store.demo)throw Error('Activity generation requires a connected workspace.');const p=Object.fromEntries(fd);await store.mutate('workflow_generate',{p_course:c.id,p_kind:p.kind,p_payload:p});});}
  function importForm(){importRows=null;modal('Review a CT import',`<p class="muted">Choose a CT tracker CSV. Review every change before applying it. Faculty ownership is never inferred from column order.</p><label class="upload-zone">${icon('upload')}<strong>Choose a CSV file</strong><span>Private preview · nothing changes yet</span><input id="import-file" type="file" accept=".csv,text/csv"></label><div id="import-preview"></div>`);$('#import-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const text=await file.text();importFingerprint=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(x=>x.toString(16).padStart(2,'0')).join('');importRows=W.previewCT(text,data());$('#import-preview').innerHTML=`<p>${importRows.length} populated CTs · ${importRows.filter(r=>r.errors.length).length} blocked · ${importRows.filter(r=>r.action==='changed').length} conflicts to review</p><div class="import-table"><table><thead><tr><th>Select</th><th>Course / CT</th><th>Existing → proposed</th><th>Review notes</th></tr></thead><tbody>${importRows.map((r,i)=>`<tr><td><input type="checkbox" data-import-row="${i}" aria-label="Apply ${esc(r.course_code)} CT ${r.ct_number}" ${r.errors.length||r.action==='unchanged'?'disabled':''}></td><td>${esc(r.course_code)}<br>CT ${r.ct_number}</td><td>${esc(r.old?.status||'New')} → ${esc(r.status)}<br>${fmt(r.old?.scheduled_date)} → ${fmt(r.scheduled_date)}</td><td>${esc([...r.errors,...r.warnings].join(' · ')||r.action)}</td></tr>`).join('')}</tbody></table></div><label class="field"><span>Reason / reconciliation note</span><input id="import-reason" required placeholder="Why is this source authoritative?"></label><button id="apply-import" class="button primary">Apply selected changes</button><p id="import-error" role="alert"></p>`;$('#apply-import').onclick=applyImport;}catch(err){$('#import-preview').textContent=err.message;}};}
  async function applyImport(){const btn=$('#apply-import');if(btn.disabled)return;btn.disabled=true;try{const rows=[...document.querySelectorAll('[data-import-row]:checked')].map(el=>importRows[+el.dataset.importRow]);if(!rows.length)throw Error('Select the reviewed changes to apply.');if(!$('#import-reason').value.trim())throw Error('Add a reconciliation reason.');if(store.demo)throw Error('The preview is available here; applying an import requires a connected workspace.');await store.mutate('workflow_import_ct',{p_term:data().term.id,p_fingerprint:importFingerprint,p_rows:rows.map(r=>({...r,expected_revision:r.old?.revision??null,id:r.old?.id||null,old:undefined})),p_reason:$('#import-reason').value});close();render();notice('Reviewed changes imported. Existing history was preserved.');}catch(e){$('#import-error').textContent=e.message;btn.disabled=false;}}
  async function action(key,attrs={}){
    if(key==='my-work'){view='tasks';render();}else if(key==='refresh')await refresh();else if(key==='new-course')courseForm();else if(key==='edit-course')courseForm(data().courses.find(c=>c.id===courseId));else if(key==='new-faculty')facultyForm();else if(key==='term')termForm();else if(key==='import')importForm();else if(key==='new-ct')newCt();else if(key==='generate')generate();else if(['prev-month','next-month','this-month'].includes(key)){calendarOffset=key==='this-month'?0:calendarOffset+(key==='prev-month'?-1:1);render();}else if(key==='account'){modal('Your workspace',`<p>${esc(name(fid()))}</p><p class="muted">${esc(W.text(store.profile.app_role))} · ${store.demo?'Fictional preview identity':'Verified faculty identity'}</p><button id="sign-out" class="button secondary">${icon('logout')} ${store.demo?'Exit preview':'Sign out'}</button>`);$('#sign-out').onclick=async()=>{if(!store.demo)await store.client.auth.signOut();location.href=location.pathname;};}else if(key==='read-notice'){try{if(store.demo)data().receipts.push({notification_id:attrs.id});else await store.query(store.client.from('notification_receipts').upsert({notification_id:attrs.id,user_id:store.profile.user_id},{onConflict:'notification_id,user_id',ignoreDuplicates:true}),'Mark read');await refresh();}catch(e){notice(e.message,'error');}}else if(key==='resolve-request'){const r=data().requests.find(r=>r.id===attrs.id);modal('Review request',`<p>${esc(r.reason)}</p><form id="editor">${select('Decision','decision',['approved','declined'])}${field('Approved deadline','date',r.proposed_date||'','date')}${select('New owner (reassignment)','owner',[['','Select faculty'],...data().faculty.map(f=>[f.id,f.full_name])])}${field('Decision reason','reason','','text','required')}${formEnd('Record decision')}`);wireSave(async fd=>{if(store.demo){r.status=fd.get('decision');r.resolution=fd.get('reason');return;}await store.mutate('workflow_resolve_request',{p_id:r.id,p_decision:fd.get('decision'),p_reason:fd.get('reason'),p_date:fd.get('date')||null,p_owner:fd.get('owner')||null});});}
  }
  function landing(mode='locked',message=''){
    $('#app').innerHTML=`<header class="landing-nav"><a class="wordmark" href="${esc(location.pathname)}"><span class="brand-symbol"><i></i><i></i><i></i></span>BME<span class="wordmark-light">Workflow</span></a><span>Biomedical Engineering · BUET</span></header><main class="landing"><p class="eyebrow">LESS ADMIN. MORE POSSIBILITY.</p><h1>Great work.<br><span>Beautifully in sync.</span></h1><p class="landing-description">A considered space for your academic day.<br>Every responsibility. Every next step. Together.</p>${mode==='auth'?`<form id="login" class="signin-card"><label class="field"><span>Your approved faculty email</span><input type="email" name="email" autocomplete="email" placeholder="you@university.edu" required></label><button class="button primary" type="submit">Email me a sign-in link ${icon('arrow')}</button><p class="small muted">Verify your email to enter your assigned workspace.</p><p id="auth-message" role="status">${esc(message)}</p></form>`:mode==='pending'?`<div class="signin-card"><h2>Awaiting approval</h2><p>Your email is verified. An administrator needs to link it to your faculty identity.</p><button id="retry-access" class="button primary">Check access again</button><button id="pending-signout" class="text-button">Sign out</button></div>`:mode==='error'?`<div class="signin-card"><h2>We couldn’t load your workspace</h2><p class="form-error">${esc(message)}</p><button id="retry-access" class="button primary">Try again</button></div>`:`<div class="landing-actions"><a class="button primary" href="?demo=1">Explore the workspace ${icon('arrow')}</a><span>Interactive preview · fictional data</span></div>`}<div class="landing-preview"><div class="preview-top"><span class="preview-dot"></span><span class="preview-dot"></span><span class="preview-dot"></span><span>Your day, thoughtfully organized</span></div><div class="preview-content"><div><p class="eyebrow">A CLEARER PICTURE</p><h2>Everything in its place.<br>You, in your element.</h2><p>From the first class to the final course file.<br>A shared rhythm for your department.</p></div><div class="preview-cards"><div>${icon('tasks')}<span>Needs my action<small>A clear next step</small></span><b>03</b></div><div>${icon('calendar')}<span>Coming up<small>A little room to plan</small></span><b>07</b></div><div>${icon('check')}<span>Completed<small>Progress worth seeing</small></span><b>12</b></div></div></div></div><p class="landing-footnote">Built around people. Protected by verified access.</p>${mode==='locked'?'<p class="setup-note">This workspace is awaiting its secure backend connection. The preview is ready to explore.</p>':''}</main>`;
    if($('#login'))$('#login').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');btn.disabled=true;btn.textContent='Sending link…';try{const {error}=await store.client.auth.signInWithOtp({email:new FormData(e.currentTarget).get('email').trim(),options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;$('#auth-message').textContent='Check your inbox for your sign-in link.';}catch(err){$('#auth-message').textContent=err.message;}finally{btn.disabled=false;btn.textContent='Email me a sign-in link';}};
    if($('#retry-access'))$('#retry-access').onclick=()=>bootstrap();if($('#pending-signout'))$('#pending-signout').onclick=()=>store.client.auth.signOut();
  }
  async function bootstrap(){
    try{
      const {data:{session},error}=await store.client.auth.getSession();if(error)throw error;if(!session){landing('auth');return;}
      const approved=await store.query(store.client.rpc('claim_allowed_profile'),'Account verification');if(!approved){landing('pending');return;}
      store.profile=await store.query(store.client.from('profiles').select('*').eq('user_id',session.user.id).single(),'Profile');
      const migrations=await store.query(store.client.from('workflow_migrations').select('version').eq('version','202609170002'),'Database compatibility');
      if(!migrations.length)throw Error('The database upgrade is pending. Apply the numbered workflow migrations before using this release.');
      await store.load();render();
    }catch(e){landing('error',e.message);}
  }
  async function init(){
    $('#dialog-close').onclick=close;$('#dialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))close();});
    if(new URLSearchParams(location.search).get('demo')==='1'&&cfg.mode!=='production'){
      await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='./demo-data.js';s.onload=resolve;s.onerror=reject;document.head.append(s);});store.data=structuredClone(window.EXAMFLOW_DEMO);Object.assign(store.data,{deadlines:[],requests:[],receipts:[],audit:[],allowed:[],outbox:[]});store.profile={user_id:'demo',faculty_id:'f3',active:true,app_role:'admin'};for(const c of store.data.courses)c.term_id=store.data.term.id;render();return;
    }
    if(cfg.mode!=='production'||!cfg.supabaseUrl||!cfg.supabaseAnonKey){landing();return;}
    if(!window.supabase){landing('error','The sign-in library could not load. Check your connection and reload.');return;}
    store=new window.WorkflowStore.Store(window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey));
    let currentUser=null;store.client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){currentUser=null;store.data={};store.profile=null;landing('auth');}else if(event==='SIGNED_IN'&&session?.user.id!==currentUser){currentUser=session.user.id;setTimeout(bootstrap,0);}});
    await bootstrap();
  }
  init().catch(e=>landing('error',e.message));
})();
